<?php

namespace AppBundle\Repository;

/**
 * AnnonceadresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceadresseRepository extends \Doctrine\ORM\EntityRepository
{

}
