<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercherAnnonces($search) {
        $qb = $this->createQueryBuilder('a')
                ->where('1=1');



        if($search['type']!= null ) {
            $qb ->andWhere('a.typepropriete >= :type')
                ->setParameter('type', $search['type']);
        }
        if($search['prix']!= null ) {
            $qb ->andWhere('a.prixnuit >= :prix')
                ->setParameter('prix', $search['prix']);
        }

        if($search['date_debut']!= null ){

            $qb ->andWhere('a.dateDepot >= :dateDebut')
                ->setParameter('dateDebut', $search['date_debut']);
        }


        if($search['date_fin']!= null ){

            $qb ->andWhere('a.dateDepot <= :dateFin')
                ->setParameter('dateFin', $search['date_fin']);
        }


        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function rechercherAnnoncesAvances($search) {
        $qb = $this->createQueryBuilder('a')
                    ->where('1=1');
            if($search['type']!= null ) {
                $qb ->andWhere('a.typepropriete = :type')
                    ->setParameter('type', $search['type']);
            }
            if($search['date_debut']!= null ) {
                $qb ->andWhere('a.dateDepot >= :dateDebut')
                    ->setParameter('dateDebut', $search['date_debut']);
            }
            if($search['date_fin']!= null ) {
                $qb ->andWhere('a.dateDepot <= :dateFin')
                    ->setParameter('dateFin', $search['date_fin']);
            }
            if($search['arrondissement']!= null ){
                $qb ->andWhere('a.arrondissement = :arrondissements')
                    ->setParameter('arrondissements', $search['arrondissement']);
            }
            if($search['prix_min']!= null ){
                $qb ->andWhere('a.prixnuit >= :prixMin')
                    ->setParameter('prixMin', $search['prix_min']);
            }
            if($search['prix_max']!= null ){
                $qb ->andWhere('a.prixnuit <= :prixMax')
                    ->setParameter('prixMax', $search['prix_max']);
            }
            if($search['surface_min']!= null ){
                $qb ->andWhere('a.superficie >= :surfaceMin')
                    ->setParameter('surfaceMin', $search['surface_min']);
            }
            if($search['surface_max']!= null ){
                $qb ->andWhere('a.superficie <= :surfaceMax')
                    ->setParameter('surfaceMax', $search['surface_max']);
            }
            if($search['piece_min']!= null ){
                $qb ->andWhere('a.piece >= :pieceMin')
                    ->setParameter('pieceMin', $search['piece_min']);
            }
            if($search['piece_max']!= null ){
                $qb ->andWhere('a.piece <= :pieceMax')
                    ->setParameter('pieceMax', $search['piece_max']);
            }
            if($search['chambre_min']!= null ){
                $qb ->andWhere('a.chambre >= :chambreMin')
                    ->setParameter('chambreMin', $search['chambre_min']);
            }
            if($search['chambre_max']!= null ){
                $qb ->andWhere('a.chambre <= :chambreMax')
                    ->setParameter('chambreMax', $search['chambre_max']);
            }



        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
