<?php

namespace AppBundle\Repository;

/**
 * CommentaireNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
